experiment_name: cornell_simple_baseline

data:
  root_dir: data/cornell_raw/cornell_grasp
  batch_size: 16
  num_workers: 4
  img_size: 224

train:
  num_epochs: 2
  lr: 0.001        # <= número, sin comillas
  weight_decay: 0.0001
  device: cpu      # de momento

model:
  name: simple_cnn  # o "resnet18" más adelante
  pretrained: false

metrics:
  iou_thresh: 0.25
  angle_thresh: 30.0

logging:
  output_dir: experiments
  save_best_by: val_success
